import React from "react";
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { ArrowLeft, MessageSquare, Bot, Star, Clock } from "lucide-react-native";
import MainContainer from "../../Common/MainContainer";
import { useTheme } from "../../Theme/ThemeContext";
import { Typography } from "../../Theme/Typographys";
import ResponsivePixels from "../../Assets/StyleUtilities/ResponsivePixels";

export default function SaveMessages() {
    const { Colors } = useTheme();
    const styles = getStyles(Colors);
    const navigation = useNavigation();

    const savedMessages = [
        {
            id: 1,
            title: "AI Recipe Suggestions",
            description: "Healthy dinner ideas generated by AI",
            icon: Bot,
            iconBg: "#4A8BFF",
            timestamp: "2 hours ago"
        },
        {
            id: 2,
            title: "Travel Itinerary",
            description: "Paris trip plan created with AI assistance",
            icon: Star,
            iconBg: "#21AF85",
            timestamp: "1 day ago"
        },
        {
            id: 3,
            title: "Meeting Notes",
            description: "AI-summarized meeting points",
            icon: MessageSquare,
            iconBg: "#9E57E5",
            timestamp: "3 days ago"
        }
    ];

    const renderMessageItem = (message: any, index: number) => {
        const isLast = index === savedMessages.length - 1;

        return (
            <View key={message.id}>
                <TouchableOpacity style={styles.messageItem} activeOpacity={0.7}>
                    <View style={[styles.iconContainer, { backgroundColor: message.iconBg }]}>
                        <message.icon color={Colors.DefaultWhite} size={20} />
                    </View>
                    <View style={styles.messageContent}>
                        <Text style={styles.messageTitle}>{message.title}</Text>
                        <Text style={styles.messageDescription}>{message.description}</Text>
                        <View style={styles.timestampContainer}>
                            <Clock color={Colors.MutedSteelText} size={14} />
                            <Text style={styles.timestampText}>{message.timestamp}</Text>
                        </View>
                    </View>
                </TouchableOpacity>
                {!isLast && <View style={styles.separator} />}
            </View>
        );
    };

    return (
        <MainContainer
            showHeader={true}
            header={{
                headerTitle: "Save Messages",
                headerLeft: {
                    customIcon: <ArrowLeft color={Colors.MidnightInkText} size={24} />,
                    onPress: () => navigation.goBack()
                }
            }}
        >
            <View style={styles.container}>
                <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scrollContent}>

                    <View style={styles.sectionContainer}>
                        <Text style={styles.sectionTitle}>AI-Generated Messages</Text>
                        <View style={styles.cardGroup}>
                            {savedMessages.map((message, index) => renderMessageItem(message, index))}
                        </View>
                    </View>

                    {savedMessages.length === 0 && (
                        <View style={styles.emptyContainer}>
                            <Bot color={Colors.MutedSteelText} size={64} />
                            <Text style={styles.emptyTitle}>No Saved Messages</Text>
                            <Text style={styles.emptyText}>Your AI-generated messages will appear here</Text>
                        </View>
                    )}

                </ScrollView>
            </View>
        </MainContainer>
    );
}

const getStyles = (Colors: any) => StyleSheet.create({
    container: {
        flex: 1,
    },
    scrollContent: {
        paddingTop: ResponsivePixels.size24,
        paddingBottom: ResponsivePixels.size60,
        paddingHorizontal: ResponsivePixels.size20,
    },
    sectionContainer: {
        marginBottom: ResponsivePixels.size24,
    },
    sectionTitle: {
        ...Typography.bodyLargePoppinsSemiBold,
        color: Colors.MidnightInkText,
        marginBottom: ResponsivePixels.size12,
        marginLeft: ResponsivePixels.size8,
    },
    cardGroup: {
        backgroundColor: Colors.DefaultWhite,
        borderRadius: ResponsivePixels.size20,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
    },
    messageItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: ResponsivePixels.size16,
        paddingHorizontal: ResponsivePixels.size16,
    },
    iconContainer: {
        width: ResponsivePixels.size40,
        height: ResponsivePixels.size40,
        borderRadius: ResponsivePixels.size12,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: ResponsivePixels.size16,
    },
    messageContent: {
        flex: 1,
    },
    messageTitle: {
        ...Typography.bodyLargePoppinsMedium,
        color: Colors.MidnightInkText,
        marginBottom: ResponsivePixels.size4,
    },
    messageDescription: {
        ...Typography.bodyMediumPoppinsRegular,
        color: Colors.MutedSteelText,
        marginBottom: ResponsivePixels.size8,
    },
    timestampContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    timestampText: {
        ...Typography.bodySmallPoppinsRegular,
        color: Colors.MutedSteelText,
        marginLeft: ResponsivePixels.size4,
    },
    separator: {
        height: 1,
        backgroundColor: Colors.FogGrey,
        opacity: 0.4,
        marginHorizontal: ResponsivePixels.size16,
    },
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: ResponsivePixels.size60,
    },
    emptyTitle: {
        ...Typography.h2RanadeBold,
        color: Colors.MidnightInkText,
        marginTop: ResponsivePixels.size16,
        marginBottom: ResponsivePixels.size8,
    },
    emptyText: {
        ...Typography.bodyMediumPoppinsRegular,
        color: Colors.MutedSteelText,
        textAlign: 'center',
    },
});

export default SaveMessages;